# Generated by Django 4.0.2 on 2022-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default='usd', max_length=3, verbose_name='amount currency'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
