# Generated by Django 4.0.2 on 2022-05-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_paymentplan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('PAYMENT_SUCCEEDED', 'payment_intent.succeeded'), ('PAYMENT_PROCESSING', 'payment_intent.processing'), ('PAYMENT_FAILED', 'payment_intent.payment_failed'), ('UNHANDLED_EVENT', 'payment_intent.unhandled_event')], default='UNHANDLED_EVENT', max_length=32, verbose_name='payment event type')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='amount to be charged')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='amount currency')),
                ('response', models.JSONField(verbose_name='payment event response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='payments.paymentplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
