# Generated by Django 4.0.2 on 2022-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='response',
            field=models.JSONField(default=dict, verbose_name='payment event response'),
        ),
    ]
