# Generated by Django 4.0.2 on 2022-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentevent_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='type',
            field=models.CharField(choices=[('payment_intent.created', 'PAYMENT_INTENT_CREATED'), ('charge.succeeded', 'CHARGE_SUCCEEDED'), ('payment_intent.succeeded', 'PAYMENT_INTENT_SUCCEEDED'), ('payment_intent.processing', 'PAYMENT_INTENT_PROCESSING'), ('payment_intent.payment_failed', 'PAYMENT_INTENT_FAILED'), ('payment_intent.unhandled_event', 'UNHANDLED_EVENT')], default='payment_intent.unhandled_event', max_length=32, verbose_name='payment event type'),
        ),
    ]
