# Generated by Django 4.0.2 on 2022-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='duration in days'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='type',
            field=models.CharField(choices=[('payment_intent.created', 'PAYMENT_INTENT_CREATED'), ('charge.succeeded', 'CHARGE_SUCCEEDED'), ('payment_intent.succeeded', 'PAYMENT_INTENT_SUCCEEDED'), ('payment_intent.processing', 'PAYMENT_INTENT_PROCESSING'), ('payment_intent.payment_failed', 'PAYMENT_INTENT_FAILED'), ('unhandled_event', 'UNHANDLED_EVENT')], default='unhandled_event', max_length=32, verbose_name='payment event type'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='amount',
            field=models.IntegerField(default=1000, help_text='1000 means 10$', verbose_name='amount to be charged'),
        ),
    ]
