# Generated by Django 4.0.2 on 2022-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=256, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=256, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.CharField(blank=True, max_length=16384, null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=256, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
    ]
