# Generated by Django 4.0.2 on 2022-03-11 11:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active_alter_event_address_alter_event_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='detail'),
        ),
    ]
