# Generated by Django 4.0.2 on 2022-05-10 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentplan_duration_alter_paymentevent_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='payments.paymentplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_plan_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment plan expires at'),
        ),
    ]
