# Generated by Django 4.0.2 on 2022-04-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.CharField(choices=[('L', 'LIKE'), ('D', 'DISLIKE'), ('N', 'NEUTRAL')], default='N', max_length=1, verbose_name='sentiment'),
        ),
    ]
