# Generated by Django 4.0.2 on 2022-04-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('L', 'LIKE'), ('D', 'DISLIKE'), ('N', 'NETURAL')], default='N', max_length=1, verbose_name='sentiment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sentiment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments_from', to=settings.AUTH_USER_MODEL)),
                ('sentiment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sentiment_to', 'sentiment_from')},
            },
        ),
    ]
