# Generated by Django 4.0.2 on 2022-03-17 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 30, 53, 730937, tzinfo=utc), verbose_name='expire at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
